import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=" m-auto p-0 flex items-center justify-center max-w-md h-screen ">
        <main className="relative rounded-xl flex h-full w-full flex-col p-10 bg-gradient-to-b from-blue-300">
          {children}
        </main>
      </body>
    </html>
  );
}
